<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <DefineConstants>MEASUREMENT_TESTS</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenMeasurementEvidence\OpenMeasurementEvidence.csproj" />
  </ItemGroup>
</Project>

